"use client";

import { useEffect, useState } from "react";
type Leaderboard = { game: { slug: string; name: string }; tournamentWeek: string; page: number; pageSize: number; entries: { rank: number; username: string; weeklyTotal: number }[] };
export function LeaderboardTable() {
  const [data, setData] = useState<Leaderboard | null>(null); const [page, setPage] = useState(1); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; void fetch(`/api/leaderboard?page=${page}&pageSize=25`, { cache: "no-store" }).then(async (response) => ({ response, body: await response.json().catch(() => null) })).then(({ response, body }) => { if (!active) return; if (!response.ok || !body) return setError("The leaderboard is temporarily unavailable."); setData(body as Leaderboard); }).catch(() => { if (active) setError("The leaderboard is temporarily unavailable."); }); return () => { active = false; }; }, [page]);
  if (error) return <p className="scores-message" role="status">{error}</p>; if (!data) return <p className="scores-message" role="status">LOADING LEADERBOARD…</p>;
  const changePage = (nextPage: number) => { setError(null); setPage(nextPage); };
  return <section className="scores-panel"><div className="scores-panel__heading"><div><p className="eyebrow">CURRENT TOURNAMENT WEEK</p><h2>{data.tournamentWeek}</h2></div><span className="scores-game-label">{data.game.name}</span></div>{data.entries.length === 0 ? <p className="muted">No public ranked scores for this week yet.</p> : <div className="scores-table scores-table--leaderboard" role="table" aria-label="Race To Win weekly leaderboard"><div className="scores-table__header" role="row"><span>POSITION</span><span>RACER</span><span>WEEKLY TOTAL</span></div>{data.entries.map((entry) => <div role="row" key={`${entry.rank}-${entry.username}`}><strong>#{entry.rank}</strong><span>{entry.username}</span><strong>{entry.weeklyTotal.toLocaleString()}</strong></div>)}</div>}<div className="scores-pagination"><button className="button button--secondary" type="button" disabled={page === 1} onClick={() => changePage(page - 1)}>PREVIOUS</button><span>PAGE {page}</span><button className="button button--secondary" type="button" disabled={data.entries.length < data.pageSize} onClick={() => changePage(page + 1)}>NEXT</button></div></section>;
}
