import type { Metadata } from "next";
import { BackLink } from "@/components/navigation/back-link";
import { ROUTES } from "@/lib/routes";

export const metadata: Metadata = { title: "Terms" };

export default function TermsPage() {
  return <section className="page-section shell narrow legal-copy"><BackLink href={ROUTES.home} /><p className="eyebrow">PROVISIONAL FRAMEWORK</p><h1>Terms of Use</h1><p className="page-lede">This page is an initial information framework. It is not final terms or a promise of availability.</p><h2>Guest Play and Scores</h2><p>Guest score displays are recreational and memory-only. Closing or reloading the page removes them. They are not tournament entries and cannot be submitted, restored, or converted into official results after registration.</p><h2>Official Competition</h2><p>Only runs started after sign-in and independently accepted by Race To Win servers may be stored, ranked, or considered for tournament eligibility. Visual browser values are not proof of an official result.</p><h2>Weekly Share Challenge</h2><p>A Share link click is not a confirmed referral or a prize. The invited player must sign in, explicitly attach the referral, confirm email, and complete the server-validated activity required by the published rules. Guest activity, browser-modified values, and unvalidated runs do not count. Weekly Share standings and any pool are determined only from server-confirmed referrals; appearing in the Top 10 is not a promise of a prize.</p><h2>Platform Status</h2><p>Race To Win is in development. Features, services, and conditions may change before launch.</p><h2>Game Participation</h2><p>Rules, requirements, restrictions, and conditions for the game will be published before it is available.</p><h2>Final Information</h2><p>Complete terms must be reviewed and published before accounts, participation, or any prize program are enabled.</p></section>;
}
